### ISSUE TITLE
Please update tags

### ISSUE THREAD

**Issue by srudchandran** [jonschlinkert/has-value#1]
Please update tags

**Comment by tunnckoCore** [comment]
Erm? What? What tags to be updated?

When opening an issue to a open source project, always try to be as descriptive as possible.

**Comment by jonschlinkert** [comment]
0.3.0 is tagged.
0.3.1 was mostly whitespace changes, and no code changes. but I can tag it

**Comment by jonschlinkert** [comment]
done

**Comment by srudchandran** [comment]
Hi,

Sorry for the short description. What I meant was the project is missing
release tags.

Sruthi
