### ISSUE TITLE
Minification failed with create react app since last version

### ISSUE THREAD

**Issue by fabiopelosin** [jonschlinkert/has-value#5]
Thank you for the handy library. Unfortunately since last the version it fails the build of create react app. More context is provided at the folling link:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

The issue also affects get-value.

**Comment by doowb** [comment]
None of the libraries you mention, nor their dependencies are using es6 features. I suggest opening an issue on `create-react-app`. If you do find an error in this library, please provide more information so I can try to reproduce the error.
